Repository WildCodeSchool/2022-09-php-orleans-project-saintay, pull requests merged in 2022-11, with the labels that each got.

#84 S02 us10
  public/assets/css/style.css
  src/View/Home/index.html.twig
  src/View/Item/_navbar.html.twig
Labels: Reviewed

#89 S2US23-Horaire-reception-Maire
  .DS_Store
  public/assets/.DS_Store
  public/assets/images/bureau_mairie.png
  src/View/Home/_mayorReception.html.twig
  src/View/Home/municipalService.html.twig
Labels: Reviewed, Correction done

#68 S1US40 PeriscolaireUS
  database.sql
  public/assets/css/periscolaire.css
  public/assets/images/periscolaire.jpg
  src/View/Home/municipalService.html.twig
Labels: Reviewed, Correction done

#88 S2US56 Home side assets
  public/assets/css/home.css
  public/assets/css/style.css
  public/assets/images/logoregioncentre.png
  public/assets/images/logorepubliquefrancaise.png
  public/assets/images/logovaldeloire.png
  public/assets/images/mairiedesaintay.jpg
  src/View/Home/_side-assets.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed, Correction done

#91 S1 us41 portail familial
  src/View/Home/municipalService.html.twig
Labels: Reviewed, Correction done

#90 S1 us39 restaurant scolaire
  src/Controller/MunicipalServiceController.php
  src/View/Home/municipalService.html.twig
Labels: Reviewed, Correction done

#95 FIXUS10 navigation buttons position fixed
  public/assets/css/style.css
  src/View/Home/index.html.twig
Labels: Reviewed

#92 FIXUS40 Bootstrap optimisation periscolaire
  public/assets/css/periscolaire.css
  src/View/Home/municipalService.html.twig
Labels: Reviewed, Correction done

#70 Sp01 us03
  public/assets/images/fredo.png
  src/View/Home/index.html.twig
Labels: Correction done

#83 S02 us02
  database.sql
  public/assets/css/style.css
  src/Controller/LoginController.php
  src/Model/UserManager.php
  src/View/Item/_navbar_login_admin.html.twig
  src/View/Login/login.html.twig
  src/View/layout_admin.html.twig
  src/routes.php
Labels: Reviewed

#77 Sp01 us37
  public/assets/css/municipalService.css
  public/assets/images/ecoleElementaire.jpeg
  public/assets/images/ecoleMaternelle.jpeg
  src/Controller/HomeController copy.php
  src/Controller/MunicipalServiceController.php
  src/Model/MunicipalServiceManager.php
  src/View/Home/municipalService.html.twig
Labels: Reviewed, Correction done

#93 FIX z-index liens non cliquable
  public/assets/css/navbar.css
  public/assets/css/root.css
  public/assets/css/style.css
  src/View/Item/_sidebar.html.twig
Labels: Reviewed

#69 Sp01 us14
  .gitignore
  config/db.php copy.dist
  database.sql
  public/assets/css/municipalite.css
  public/assets/images/Lequipe-Municipal.jpg
  public/upload/DominiquePortrait.png
  public/upload/MairePortrait.png
  public/upload/Marie-francoisePortrait.png
  public/upload/PascalPortrait.png
  src/Controller/HomeController.php
  src/Controller/MunicipaliteTeamController.php
  src/Model/ItemManager copy.php
  src/Model/MunicipaliteTeamManager.php
  src/View/Municipalite/index.html.twig
  src/routes.php
Labels: Reviewed, Correction done

#98 fix on home page
  public/assets/css/style.css
  src/View/Home/index.html.twig
  src/View/Urbanism/urbanism.html.twig
Labels: Reviewed, Correction done

#94 S02 us29
  public/assets/css/style.css
  src/View/Contact/contact.html.twig
  src/View/Urbanism/urbanism.html.twig
Labels: Reviewed, Correction done

#99 admin dashboard layout created
  public/assets/css/navbar.css
  public/assets/images/Vector.svg
  src/View/Contact/contact.html.twig
  src/View/Item/_navbar_dashboard_admin.html.twig
  src/View/layout_admin.html.twig
Labels: Reviewed

#102 Sp02 us36
  public/assets/images/childCare.jpg
  src/View/Home/_childCare.html.twig
  src/View/Home/municipalService.html.twig
Labels: Reviewed

#76 FIX Sp01 us28
  public/assets/css/root.css
  public/assets/css/style.css
  public/assets/images/Pompiers.png
  public/assets/images/pompier1.jpg
  src/View/Home/municipalService.html.twig
Labels: Reviewed, Correction done

#104 S2US55 actuality page(all)
  composer.json
  composer.lock
  public/assets/css/actuality-cards.css
  public/assets/css/home.css
  public/assets/css/root.css
  src/Controller/AbstractController.php
  src/Controller/HomeController.php
  src/View/Home/_actuality-card.html.twig
  src/View/Home/_actuality.html.twig
  src/View/Home/all-actualities.html.twig
  src/View/Home/index.html.twig
  src/routes.php
Labels: Reviewed

#107 S2US27 Library
  public/assets/css/municipalService.css
  public/assets/images/library.jpg
  src/View/Home/_library.html.twig
  src/View/Home/_mayorReception.html.twig
  src/View/Home/municipalService.html.twig
Labels: Reviewed

#111 fix db.php
  config/db.php.dist
Labels: Reviewed

#108 S2US25 Postal Agency
  .DS_Store
  public/assets/.DS_Store
  public/assets/css/municipalService.css
  public/assets/images/postal.jpg
  src/View/Home/_postalAgency.html.twig
  src/View/Home/municipalService.html.twig
Labels: Reviewed, Correction done

#112 DEV TO MAIN
  .DS_Store
  composer.json
  composer.lock
  config/db.php.dist
  public/assets/.DS_Store
  public/assets/css/actuality-cards.css
  public/assets/css/home.css
  public/assets/css/municipalService.css
  public/assets/css/root.css
  public/assets/css/style.css
  public/assets/images/Pompiers.png
  public/assets/images/childCare.jpg
  public/assets/images/library.jpg
  public/assets/images/pompier1.jpg
  public/assets/images/postal.jpg
  src/Controller/AbstractController.php
  src/Controller/HomeController.php
  src/View/Home/_actuality-card.html.twig
  src/View/Home/_actuality.html.twig
  src/View/Home/_childCare.html.twig
  src/View/Home/_library.html.twig
  src/View/Home/_mayorReception.html.twig
  src/View/Home/_postalAgency.html.twig
  src/View/Home/all-actualities.html.twig
  src/View/Home/index.html.twig
  src/View/Home/municipalService.html.twig
  src/routes.php
Labels: Reviewed

#113 S2US35 Market & Cinema infos
  src/View/Home/_cinema.html.twig
  src/View/Home/_market.html.twig
  src/View/Home/municipalService.html.twig
Labels: Reviewed

#116 Fix sql
  database.sql
  src/View/Home/municipalService.html.twig
Labels: Reviewed

#118 DEV TO MAIN Stable
  database.sql
  src/View/Home/_cinema.html.twig
  src/View/Home/_market.html.twig
  src/View/Home/municipalService.html.twig
Labels: Reviewed

#110 S2US8 split part 2 _Admin can Create an actuality
  src/Controller/AdminActualityController.php
  src/Model/ActualityManager.php
  src/View/Admin/admin-add-actuality.html.twig
  src/routes.php
Labels: Reviewed, Correction done

#117 S2US12 city heritage (history)
  src/Controller/HistoryController.php
  src/View/History/_city-heritage.html.twig
  src/View/History/history.html.twig
  src/routes.php
Labels: Reviewed

#119 S02US33 city map
  src/Controller/CityMapController.php
  src/View/CityMap/city_map.html.twig
  src/routes.php
Labels: Reviewed

#122 S02 us32 landfill section
  src/View/Home/_landfill.html.twig
  src/View/Home/municipalService.html.twig
Labels: Reviewed

#123 S02US29 update text display urbanism page
  src/View/Urbanism/urbanism.html.twig
Labels: Reviewed

#115 S2US8 split part1 Admin Show All Actuality
  src/Controller/AdminActualityController.php
  src/Controller/AdminController.php
  src/Model/ActualityManager.php
  src/View/Admin/admin-actuality.html.twig
  src/View/Admin/admin-add-actuality.html.twig
  src/View/Admin/admin.html.twig
  src/routes.php
Labels: Reviewed, Correction done

#125 FIX adding side-bar
  src/View/Municipalite/index.html.twig
Labels: Reviewed

#103 SP02-US34
  public/assets/images/babySitting.jpg
  src/View/Home/municipalService.html.twig
  src/View/Item/_babySitting.html.twig
Labels: Reviewed, Correction done

#124 FIX nav-bar-links & shortcut-links
  src/View/Home/index.html.twig
  src/View/Home/municipalService.html.twig
  src/View/Item/_navbar.html.twig
  src/routes.php
Labels: Reviewed, Correction done

#131 DEV TO MAIN stable -> presentation
  public/assets/images/agylus_vitrail.jpg
  public/assets/images/babySitting.jpg
  public/assets/images/monument_aux_morts.jpg
  src/Controller/AdminActualityController.php
  src/Controller/AdminController.php
  src/Controller/CityMapController.php
  src/Controller/HistoryController.php
  src/Model/ActualityManager.php
  src/View/Admin/admin-actuality.html.twig
  src/View/Admin/admin-add-actuality.html.twig
  src/View/Admin/admin.html.twig
  src/View/CityMap/city_map.html.twig
  src/View/History/_city-heritage.html.twig
  src/View/History/history.html.twig
  src/View/Home/_landfill.html.twig
  src/View/Home/index.html.twig
  src/View/Home/municipalService.html.twig
  src/View/Item/_babySitting.html.twig
  src/View/Item/_navbar.html.twig
  src/View/Municipalite/index.html.twig
  src/View/Urbanism/urbanism.html.twig
  src/routes.php
Labels: Reviewed

#133 S2US7 Admin delete function
  src/Controller/AdminActualityController.php
  src/Model/ActualityManager.php
  src/View/Admin/admin-actuality.html.twig
  src/View/layout_admin.html.twig
  src/routes.php
Labels: Reviewed

#139 REWORK Municipal services
  public/assets/css/municipalService.css
  public/assets/css/style.css
  public/assets/images/services.jpg
  src/Controller/MunicipalServiceController.php
  src/View/Home/_childCare.html.twig
  src/View/Home/municipalService.html.twig
  src/View/Item/_babySitting.html.twig
  src/View/Item/_sidebar.html.twig
  src/View/Municipal-services/_babySitting.html.twig
  src/View/Municipal-services/_childCare.html.twig
  src/View/Municipal-services/_cinema.html.twig
  src/View/Municipal-services/_family_portal.html.twig
  src/View/Municipal-services/_firemens.html.twig
  src/View/Municipal-services/_landfill.html.twig
  src/View/Municipal-services/_library.html.twig
  src/View/Municipal-services/_market.html.twig
  src/View/Municipal-services/_mayorReception.html.twig
  src/View/Municipal-services/_periscolar.html.twig
  src/View/Municipal-services/_postalAgency.html.twig
  src/View/Municipal-services/_school.html.twig
  src/View/Municipal-services/municipalService.html.twig
Labels: Reviewed

#140 FIX Actuality button style (biggest PR ever)
  src/View/Home/_actuality.html.twig
Labels: Reviewed

#144 FIX Adding Hover effect on NavBar
  public/assets/css/navbar.css
  public/assets/css/root.css
  src/View/Item/_navbar.html.twig
Labels: Reviewed

#134 S02US18 reports page created
  database.sql
  public/assets/css/report-card.css
  public/assets/images/arrete-municipal.jpg
  public/assets/images/logo-conseil-municipal.png
  public/assets/images/reunion-conseil.png
  src/Controller/ReportController.php
  src/Model/ActualityManager.php
  src/Model/ReportManager.php
  src/View/Report/reports.html.twig
  src/routes.php
Labels: Reviewed, Correction done

#143 FIX navbar & sidebar
  public/assets/css/root.css
  public/assets/css/style.css
  src/View/Item/_sidebar.html.twig
Labels: Reviewed, Conflict Resolved

#145 Transport en commun
  src/View/Municipal-services/_publicTransport.html.twig
  src/View/Municipal-services/municipalService.html.twig
Labels: Reviewed, Correction done

#150 S3US62 Association Home Page
  public/assets/css/association.css
  public/assets/images/association.jpg
  src/Controller/AssociationController.php
  src/View/Association/home-association.html.twig
  src/routes.php
Labels: Reviewed

#136 S2US53 ADD_municipal agent
  .gitignore
  public/assets/css/municipalite.css
  public/uploads/.gitignore
  public/uploads/DominiquePortrait.png
  public/uploads/MairePortrait.png
  public/uploads/Marie-francoisePortrait.png
  public/uploads/PascalPortrait.png
  src/Controller/AdminMunicipaliteTeamController.php
  src/Model/MunicipaliteTeamManager.php
  src/View/Municipalite/add.html.twig
  src/View/Municipalite/admin.html.twig
  src/routes.php
Labels: Reviewed, Correction done

#149 Sp03 us24 Membres de la commune
  database.sql
  public/assets/css/municipalite.css
  public/uploads/DominiquePortrait.png
  public/uploads/MairePortrait.png
  public/uploads/Marie-francoisePortrait.png
  public/uploads/PascalPortrait.png
  src/Controller/MunicipalServiceController.php
  src/Model/MunicipaliteTeamManager.php
  src/View/Municipal-services/_commun-team.html.twig
  src/View/Municipal-services/municipalService.html.twig
  src/routes.php
Labels: Reviewed, Conflict Resolved

#154 Fix-Image SERVICE MUNICIPAUX
  src/View/Municipal-services/_childCare.html.twig
  src/View/Municipal-services/_periscolar.html.twig
  src/View/Municipal-services/_school.html.twig
Labels: Reviewed

#155 FIX DB problem
  database.sql
  src/Model/AssociationManager.php
Labels: Reviewed

#156 FIX_history Adjusting visuals
  public/assets/css/style.css
  public/assets/images/history.jpg
  src/View/History/_city-heritage.html.twig
Labels: Reviewed

#160 FIX side/bar
  src/View/Municipal-services/municipalService.html.twig
Labels: Reviewed, Correction done

#163 Fix issues for dev to main
  database.sql
  src/Model/ActualityManager.php
  src/View/Admin/admin.html.twig
  src/View/Home/index.html.twig
  src/View/Item/_navbar.html.twig
  src/View/Item/_navbar_dashboard_admin.html.twig
  src/View/Item/_navbar_login_admin.html.twig
  src/View/Municipalite/add.html.twig
  src/View/Municipalite/admin.html.twig
  src/View/layout_admin.html.twig
Labels: Reviewed

#164 FIX Page admin municipalite
  database.sql
  src/Controller/AdminMunicipaliteTeamController.php
  src/Controller/MunicipaliteTeamController.php
  src/Model/MunicipaliteTeamManager.php
  src/View/Municipalite/add.html.twig
Labels: Reviewed

#151 S03 us59 add report
  .gitignore
  database.sql
  src/Controller/AdminReportController.php
  src/Model/CategoryManager.php
  src/Model/ReportManager.php
  src/View/Admin/admin-add-report.html.twig
  src/View/Admin/admin-report.html.twig
  src/View/Report/reports.html.twig
  src/routes.php
Labels: Reviewed, Conflict Resolved

#159 S3US3 mot du maire
  database.sql
  saint_ay.sql
  src/Controller/HomeController.php
  src/Model/WordMayorManager.php
  src/View/Home/index.html.twig
Labels: Reviewed, Correction done

#167 SP03-PageLegalNotice
  src/Controller/HomeController.php
  src/View/Home/index.html.twig
  src/View/Home/mentions-legales.html.twig
  src/routes.php
Labels: Reviewed

#171 S03US60 edit report
  src/Controller/AdminReportController.php
  src/Model/ReportManager.php
  src/View/Admin/_form-admin-report.html.twig
  src/View/Admin/admin-edit-report.html.twig
  src/View/Admin/admin-report.html.twig
  src/routes.php
Labels: Reviewed

#173 FIX DB PROBLEM (again)
  database.sql
Labels: Reviewed

#170 SP03 US63 Finish dynamic openingTime and contact
  database.sql
  src/Controller/AdminScheduleController.php
  src/Controller/HomeController.php
  src/Model/ContactInformationManager.php
  src/Model/ScheduleManager.php
  src/View/Admin/admin-openingTime.html.twig
  src/View/Admin/admin.html.twig
  src/View/Home/index.html.twig
  src/routes.php
Labels: Reviewed, Conflict Resolved

#174 S03US61 delete report
  src/Controller/AdminReportController.php
  src/View/Admin/admin-report.html.twig
  src/routes.php
Labels: Reviewed, Conflict Resolved

#175 Fix word placeholder
  database.sql
  src/View/Home/index.html.twig
Labels: Reviewed

#176 FIX des dégâts
  database.sql
  src/Controller/AdminScheduleController.php
  src/View/Admin/admin-actuality.html.twig
  src/View/Admin/admin-association.html.twig
  src/View/Admin/admin-report.html.twig
  src/View/Admin/admin-schedule.html.twig
  src/View/Admin/admin.html.twig
  src/View/Home/index.html.twig
  src/View/Municipalite/admin.html.twig
  src/routes.php
Labels: Reviewed

#162 S3 us45 add association
  database.sql
  src/Controller/AssociationController.php
  src/Model/AssociationManager.php
  src/View/Admin/_form-admin-association.html.twig
  src/View/Admin/admin-actuality.html.twig
  src/View/Admin/admin-add-association.html.twig
  src/View/Admin/admin-association.html.twig
  src/View/Admin/admin-report.html.twig
  src/View/Admin/admin.html.twig
  src/routes.php
Labels: Reviewed, Conflict Resolved

#178 Fix municipalité Little rework
  public/assets/css/municipalite.css
  public/assets/images/municipalite.jpg
  src/Controller/MunicipaliteTeamController.php
  src/View/Municipalite/index.html.twig
  src/View/Municipalite/municipalTeam.html.twig
  src/routes.php
Labels: Reviewed

#179 FIX font-size general
  public/assets/css/actuality-cards.css
  public/assets/css/style.css
  src/View/Association/_association-card.html.twig
  src/View/History/_city-heritage.html.twig
  src/View/Municipal-services/_library.html.twig
  src/View/Municipal-services/_postalAgency.html.twig
Labels: Reviewed

#180 FIX association card style
  public/assets/css/association.css
  src/View/Association/_association-card.html.twig
  src/View/Association/_associations.html.twig
Labels: Reviewed, Conflict Resolved

#182 FIX add little Footer for legal notice
  public/assets/css/root.css
  public/assets/css/style.css
  src/View/Home/index.html.twig
  src/View/Home/mentions-legales.html.twig
  src/View/Item/_footer.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#184 FIX login fail
  database.sql
  src/Controller/LoginController.php
Labels: Reviewed

#188 ADD_REPORT_CONTENT insert reports into database
  database.sql
Labels: Reviewed

#181 FIX sidebar
  public/assets/css/style.css
  src/View/Item/_sidebar.html.twig
Labels: Reviewed, Conflict Resolved

#194 S3 us46 edit association
  src/Controller/AssociationController.php
  src/Model/AssociationManager.php
  src/View/Admin/_form-admin-association.html.twig
  src/View/Admin/admin-association.html.twig
  src/View/Admin/admin-edit-association.html.twig
  src/routes.php
Labels: Reviewed, User Story

#191 S4US? DELETE Communal Agent
  src/Controller/AdminMunicipaliteTeamController.php
  src/View/Admin/admin-communal-team.html.twig
  src/routes.php
Labels: Reviewed

#186 FIX Placeholder
  database.sql
  public/assets/images/placeholder.jpg
  src/View/Municipal-services/_commun-team.html.twig
  src/View/Municipalite/index.html.twig
Labels: Reviewed, Conflict Resolved

#185 FIX_SESSION mise en place de la session
  public/index.php
  src/Controller/AbstractController.php
  src/Controller/AdminController.php
  src/Controller/LoginController.php
  src/View/Error404/error404.html.twig
  src/View/Item/_navbar_dashboard_admin.html.twig
  src/routes.php
Labels: Reviewed, Conflict Resolved

#193 Fix Page admin municipaliteTeam CRUD EDIT #177
  src/Controller/AdminMunicipaliteTeamController.php
  src/View/Municipalite/add.html.twig
  src/View/Municipalite/edit.html.twig
Labels: Reviewed, Correction done

#187 S4US? Show All Communal Team
  src/View/Admin/admin-communal-team.html.twig
  src/View/Admin/admin.html.twig
Labels: Reviewed, Conflict Resolved

#195 S4US47 delete association
  src/Controller/AssociationController.php
  src/Model/AssociationManager.php
  src/View/Admin/admin-association.html.twig
  src/View/Association/_association-card.html.twig
  src/routes.php
Labels: Reviewed, Conflict Resolved

#190 S4US? EDIT Communal Team
  src/Controller/AdminMunicipaliteTeamController.php
  src/Model/MunicipaliteTeamManager.php
  src/View/Admin/admin-communal-team.html.twig
  src/View/Admin/admin-edit-communal-team.html.twig
  src/routes.php
Labels: Reviewed, Conflict Resolved

#197 Fix admin Page Municipalité
  database.sql
  src/View/Municipalite/admin.html.twig
Labels: Reviewed

#199 FIX_SESSION update secure admin
  src/Controller/AbstractController.php
  src/Controller/AdminActualityController.php
  src/Controller/AdminMunicipaliteTeamController.php
  src/Controller/AdminReportController.php
  src/Controller/AdminScheduleController.php
  src/Controller/AdminWordMayorController.php
  src/Controller/AssociationController.php
Labels: Reviewed

#203 Updates done on img FIX_History
  public/assets/css/style.css
  public/assets/images/monument_aux_morts.jpg
  public/assets/images/monument_aux_morts_saint-ay.jpg
  src/Controller/AdminMunicipaliteTeamController.php
  src/View/History/_city-heritage.html.twig
Labels: Reviewed, Correction done

#202 CRUD EDIT Page Horaires finish
  src/Controller/AdminContactInfoController.php
  src/Controller/AdminMunicipaliteTeamController.php
  src/Controller/AdminScheduleController.php
  src/Model/ContactInformationManager.php
  src/Model/ScheduleManager.php
  src/View/Admin/_form-admin-contactInfo.html.twig
  src/View/Admin/_form-admin-schedule.html.twig
  src/View/Admin/admin-schedule.html.twig
  src/routes.php
Labels: Reviewed, Correction done

#205 FIX_SESSION update secure all admin side
  src/Controller/AdminContactInfoController.php
  src/Controller/AdminMunicipaliteTeamController.php
  src/Controller/AdminScheduleController.php
Labels: Reviewed

#206 Fix-GAP-Button-Horaires
  src/View/Admin/admin-schedule.html.twig
  src/View/Municipalite/admin.html.twig
Labels: Reviewed

#189 S4US? ADD Communal Agent
  src/Controller/AdminMunicipaliteTeamController.php
  src/Model/MunicipaliteTeamManager.php
  src/View/Admin/admin-communal-team-add.html.twig
  src/View/Admin/admin-communal-team.html.twig
  src/routes.php
Labels: Reviewed, Conflict Resolved

#207 textarea/wordmayor
  src/View/Admin/_form-admin-word.html.twig
Labels: Reviewed

#204 size/commune card
  public/assets/css/municipalite.css
  src/View/Municipal-services/_commun-team.html.twig
Labels: Reviewed

#209 Add style on the Fix_sentence
  src/View/Home/_wordMayor.html.twig
Labels: Reviewed, Fix

#210 Change the img to Fix_history
  public/assets/images/monument_aux_morts_saint-ay.jpg
Labels: Reviewed

#198 FIX Municipal Home Page Doublons + placeHolder fail
  src/Controller/AdminMunicipaliteTeamController.php
  src/View/Municipalite/index.html.twig
  src/View/Municipalite/municipalTeam.html.twig
Labels: Reviewed, Conflict Resolved

#208 Fix-Page-Municipalite-View
  public/assets/css/municipalite.css
  src/Controller/MunicipaliteTeamController.php
  src/View/Municipalite/index.html.twig
Labels: Reviewed, Conflict Resolved

#211 Fix-Horaires-Ul-Li
  public/assets/css/municipalite.css
  src/View/Home/_wordMayor.html.twig
  src/View/Home/index.html.twig
  src/View/Municipalite/index.html.twig
Labels: Reviewed, Correction done

#251 faute/orthographe "."
  src/View/Municipal-services/_publicTransport.html.twig
Labels: Reviewed

#215 update to Fix_sentence
  src/View/Home/_wordMayor.html.twig
Labels: Reviewed, Fix

#253 FIX_CRUD_REPORT
  src/Controller/AdminReportController.php
Labels: Reviewed

#252 FIX_SIDEBAR_ADMINupdate navigation links
  src/View/Admin/_form-admin-schedule.html.twig
  src/View/Admin/admin-actuality.html.twig
  src/View/Admin/admin-association.html.twig
  src/View/Admin/admin-communal-team-add.html.twig
  src/View/Admin/admin-communal-team.html.twig
  src/View/Admin/admin-edit-report.html.twig
  src/View/Admin/admin-report.html.twig
  src/View/Admin/admin-schedule.html.twig
  src/View/Admin/admin.html.twig
  src/View/Admin/adminWordsMayor.html.twig
  src/View/Admin/editWordMayor.html.twig
  src/View/Municipalite/admin.html.twig
  src/View/Municipalite/edit.html.twig
Labels: Reviewed

#258 FIX SIDEBAR VISITOR update
  src/View/Association/association.html.twig
  src/View/Association/home-association.html.twig
  src/View/CityMap/city_map.html.twig
  src/View/History/history.html.twig
  src/View/Home/all-actualities.html.twig
  src/View/Municipal-services/municipalService.html.twig
  src/View/Municipalite/index.html.twig
  src/View/Report/reports.html.twig
  src/View/Urbanism/urbanism.html.twig
Labels: Reviewed

#259 FIX_NAVIGATION_LINKS update
  src/View/Urbanism/urbanism.html.twig
Labels: Reviewed

#257 photomayor
  src/View/Home/_wordMayor.html.twig
Labels: Reviewed

#256 actu/ordre_chrono
  database.sql
Labels: Reviewed

#255 Fix-Crud-Municipalite
  src/View/Admin/_form-admin-contactInfo.html.twig
  src/View/Admin/_form-admin-schedule.html.twig
  src/View/Municipalite/add.html.twig
  src/View/Municipalite/edit.html.twig
Labels: Reviewed

#261 Fix - preparing for demo-day
  database.sql
Labels: Reviewed, Correction done

#262 FIX_REPORTS fix report page visitor/admin
  src/Controller/AdminReportController.php
  src/Model/ReportManager.php
  src/View/Admin/admin-add-report.html.twig
  src/View/Report/reports.html.twig
Labels: Reviewed

#264 FIX sidebar_nav_admin
  src/View/Admin/admin-actuality.html.twig
  src/View/Admin/admin-association.html.twig
  src/View/Admin/admin-communal-team.html.twig
  src/View/Admin/admin-report.html.twig
  src/View/Admin/admin-schedule.html.twig
  src/View/Admin/adminWordsMayor.html.twig
  src/View/Municipalite/admin.html.twig
Labels: Reviewed

#263 placeholder_MAYOR
  database.sql
  src/View/Home/_wordMayor.html.twig
Labels: Reviewed

#213 Fix service municipaux
  src/View/Municipal-services/_babySitting.html.twig
  src/View/Municipal-services/_camping.html.twig
  src/View/Municipal-services/_childCare.html.twig
  src/View/Municipal-services/_cinema.html.twig
  src/View/Municipal-services/_family_portal.html.twig
  src/View/Municipal-services/_firemens.html.twig
  src/View/Municipal-services/_landfill.html.twig
  src/View/Municipal-services/_library.html.twig
  src/View/Municipal-services/_market.html.twig
  src/View/Municipal-services/_mayorReception.html.twig
  src/View/Municipal-services/_periscolar.html.twig
  src/View/Municipal-services/_postalAgency.html.twig
  src/View/Municipal-services/_publicTransport.html.twig
  src/View/Municipal-services/_school.html.twig
Labels: Reviewed

#260 Add bold to text - FIX_History
  src/View/History/_city-heritage.html.twig
  src/View/History/history.html.twig
Labels: Reviewed

#268 FIX Category Class update
  src/View/Admin/_form-admin-report.html.twig
  src/View/Admin/admin-add-report.html.twig
Labels: Reviewed

#269 actu/nl2b
  public/assets/css/actuality-cards.css
  src/View/Home/_actuality-card.html.twig
Labels: Reviewed

#270 Fix-Card-Municipalite
  src/View/Municipalite/index.html.twig
Labels: Reviewed, Conflict Resolved

#271 Verification done on message d'error
  src/Controller/AssociationController.php
  src/View/Admin/_form-admin-association.html.twig
Labels: Reviewed, Correction done

#272 FIX reorga clean and full fonctionnal
  src/Controller/MunicipalServiceController.php
  src/Controller/MunicipaliteTeamController.php
  src/View/CityMap/city_map.html.twig
  src/View/Municipal-services/municipalService.html.twig
  src/View/Municipalite/_commun-team.html.twig
  src/View/Municipalite/communalTeam.html.twig
  src/View/Municipalite/index.html.twig
  src/View/Municipalite/municipalTeam.html.twig
  src/View/Report/reports.html.twig
  src/View/Urbanism/urbanism.html.twig
  src/routes.php
Labels: Reviewed, Correction done

#266 Dev To Main
  database.sql
  public/assets/css/actuality-cards.css
  src/Controller/AdminMunicipaliteTeamController.php
  src/Controller/AdminReportController.php
  src/Controller/AssociationController.php
  src/Controller/MunicipalServiceController.php
  src/Controller/MunicipaliteTeamController.php
  src/Model/ReportManager.php
  src/View/Admin/_form-admin-association.html.twig
  src/View/Admin/_form-admin-contactInfo.html.twig
  src/View/Admin/_form-admin-report.html.twig
  src/View/Admin/_form-admin-schedule.html.twig
  src/View/Admin/admin-actuality.html.twig
  src/View/Admin/admin-add-report.html.twig
  src/View/Admin/admin-association.html.twig
  src/View/Admin/admin-communal-team-add.html.twig
  src/View/Admin/admin-communal-team.html.twig
  src/View/Admin/admin-edit-report.html.twig
  src/View/Admin/admin-report.html.twig
  src/View/Admin/admin-schedule.html.twig
  src/View/Admin/admin.html.twig
  src/View/Admin/adminWordsMayor.html.twig
  src/View/Admin/editWordMayor.html.twig
  src/View/Association/association.html.twig
  src/View/Association/home-association.html.twig
  src/View/CityMap/city_map.html.twig
  src/View/History/_city-heritage.html.twig
  src/View/History/history.html.twig
  src/View/Home/_actuality-card.html.twig
  src/View/Home/_wordMayor.html.twig
  src/View/Home/all-actualities.html.twig
  src/View/Municipal-services/_babySitting.html.twig
  src/View/Municipal-services/_camping.html.twig
  src/View/Municipal-services/_childCare.html.twig
  src/View/Municipal-services/_cinema.html.twig
  src/View/Municipal-services/_family_portal.html.twig
  src/View/Municipal-services/_firemens.html.twig
  src/View/Municipal-services/_landfill.html.twig
  src/View/Municipal-services/_library.html.twig
  src/View/Municipal-services/_market.html.twig
  src/View/Municipal-services/_mayorReception.html.twig
  src/View/Municipal-services/_periscolar.html.twig
  src/View/Municipal-services/_postalAgency.html.twig
  src/View/Municipal-services/_publicTransport.html.twig
  src/View/Municipal-services/_school.html.twig
  src/View/Municipal-services/municipalService.html.twig
  src/View/Municipalite/_commun-team.html.twig
  src/View/Municipalite/add.html.twig
  src/View/Municipalite/admin.html.twig
  src/View/Municipalite/communalTeam.html.twig
  src/View/Municipalite/edit.html.twig
  src/View/Municipalite/index.html.twig
  src/View/Municipalite/municipalTeam.html.twig
  src/View/Report/reports.html.twig
  src/View/Urbanism/urbanism.html.twig
  src/View/layout_admin.html.twig
  src/routes.php
Labels: Reviewed

#274 FIX actu-cards
  public/assets/css/actuality-cards.css
Labels: Fix

#275 Dev To Main
  public/assets/css/actuality-cards.css
Labels: Reviewed

#277 FIX url image
  src/View/Home/_wordMayor.html.twig
Labels: Reviewed
