Repository WildCodeSchool/2022-09-php-orleans-project-saintay, pull requests merged in 2022-10, with the labels that each got.

#1 Init
  public/assets/css/root.css
  public/assets/css/style.css
  src/View/layout.html.twig
Labels: Reviewed, Correction done

#60 So1 fixinit
  .DS_Store
  .gitignore
  public/assets/.DS_Store
  public/assets/css/root.css
  public/assets/css/style.css
  public/assets/font/Marianne-Bold.woff
  public/assets/font/Marianne-Medium.woff
  src/View/layout.html.twig
Labels: Reviewed

#61 So1 us1 navbar
  public/assets/css/navbar.css
  public/assets/css/style.css
  public/assets/images/logo.png
  src/View/Item/_navbar.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#67 S01 us48
  public/assets/css/root.css
  public/assets/css/style.css
  saint_ay.sql
  src/Controller/ContactController.php
  src/View/Contact/contact.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: Reviewed, Correction done

#64 S1 us1bis sidebar
  public/assets/css/style.css
  src/Controller/AbstractController.php
  src/Controller/ItemController.php
  src/View/Home/index.html.twig
  src/View/Item/_sidebar.html.twig
  src/View/layout.html.twig
Labels: Conflict, Reviewed, Correction done

#71 S1U05_actus-display
  .DS_Store
  database.sql
  public/assets/.DS_Store
  public/assets/css/style.css
  public/assets/images/homme-devant-ordinateur.jpg
  public/assets/images/incendie_saintay.jpeg
  public/assets/images/marcheur_agyliens.jpeg
  src/Controller/HomeController.php
  src/Model/ActualityManager.php
  src/View/Home/_actuality.html.twig
  src/View/Home/index.html.twig
Labels: Reviewed, Correction done

#74 S1 FIX2 MAIN FIX TO DEV
  public/assets/css/style.css
  src/View/Contact/contact.html.twig
  src/View/Home/index.html.twig
  src/View/Item/_navbar.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#66 Sp01 us28
  public/assets/css/style.css
  public/assets/images/Pompiers.png
  src/Controller/MunicipalServiceController.php
  src/View/Home/municipalService.html.twig
  src/routes.php
Labels: Reviewed, Correction done

#75 DEV TO MAIN Fix
  .github/workflows/deploy.yml
  public/assets/css/style.css
  public/assets/images/Pompiers.png
  public/index.php
  src/Controller/MunicipalServiceController.php
  src/View/Contact/contact.html.twig
  src/View/Home/index.html.twig
  src/View/Home/municipalService.html.twig
  src/View/Item/_navbar.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: Change request

#63 S1US13 coordonnées
  public/assets/css/style.css
  src/View/Home/index.html.twig
Labels: Reviewed, Correction done

#81 FIX fontface & navbar alignement problem
  public/assets/css/root.css
  src/View/Item/_navbar.html.twig
  src/View/layout.html.twig
Labels: Reviewed
